package ast;

public enum TipoE {
	NOMBREVARIABLE, NUMERO,
	OPMAS, OPMENOS,
	OPMUL, OPDIV,
	OPMAYOR, OPMENOR, OPMAYORIGUAL, OPMENORIGUAL, OPDISTINTO, OPIGUAL,
	OPASIGNACION,
	OPOR, OPAND,
	OPNOT, OPMENOSUNARIO
}
