/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package descendente;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int digito = 1;
  /** RegularExpression Id. */
  int signo = 2;
  /** RegularExpression Id. */
  int NUMERO = 3;
  /** RegularExpression Id. */
  int SEPARADOR = 4;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 5;
  /** RegularExpression Id. */
  int NOMBRETIPONUM = 6;
  /** RegularExpression Id. */
  int NOMBRETIPOBOOL = 7;
  /** RegularExpression Id. */
  int OPMUL = 8;
  /** RegularExpression Id. */
  int OPDIV = 9;
  /** RegularExpression Id. */
  int OPAND = 10;
  /** RegularExpression Id. */
  int OPOR = 11;
  /** RegularExpression Id. */
  int OPNOT = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int OPASIGNAR = 15;
  /** RegularExpression Id. */
  int OPMENOR = 16;
  /** RegularExpression Id. */
  int OPMAYOR = 17;
  /** RegularExpression Id. */
  int OPMENORIGUAL = 18;
  /** RegularExpression Id. */
  int OPMAYORIGUAL = 19;
  /** RegularExpression Id. */
  int OPIGUAL = 20;
  /** RegularExpression Id. */
  int OPDISTINTO = 21;
  /** RegularExpression Id. */
  int PAP = 22;
  /** RegularExpression Id. */
  int PCI = 23;
  /** RegularExpression Id. */
  int letra = 24;
  /** RegularExpression Id. */
  int NOMBREVARIABLE = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<digito>",
    "<signo>",
    "<NUMERO>",
    "\"&&\"",
    "\";\"",
    "\"num\"",
    "\"bool\"",
    "\"*\"",
    "\"/\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"true\"",
    "\"false\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\"=>\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "<letra>",
    "<NOMBREVARIABLE>",
    "<token of kind 26>",
    "\"-\"",
    "\"+\"",
  };

}
