
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 06 11:39:24 CEST 2019
//----------------------------------------------------

package ascendente.asint;

import java_cup.runtime.*;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import ascendente.alex.AnalizadorLexicoTiny;
import ascendente.alex.UnidadLexica;
import ascendente.errors.GestionErroresTiny;
import ast.asignaciones.ACompuesta;
import ast.asignaciones.ASimple;
import ast.Programa;
import ast.asignaciones.Asignacion;
import ast.asignaciones.I;
import ast.asignaciones.IS;
import ast.declaraciones.*;
import ast.expresiones.E;
import ast.expresiones.eBin.*;
import ast.expresiones.eUn.*;
import ast.terminales.BoolFalse;
import ast.terminales.BoolTrue;
import ast.terminales.NombreVariable;
import ast.terminales.Numero;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Mon May 06 11:39:24 CEST 2019
  */
public class AnalizadorSintacticoTiny extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoTiny() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoTiny(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoTiny(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\042\000\002\002\005\000\002\002\004\000\002\003" +
    "\005\000\002\003\003\000\002\004\004\000\002\004\004" +
    "\000\002\005\005\000\002\005\003\000\002\006\005\000" +
    "\002\007\004\000\002\007\004\000\002\007\003\000\002" +
    "\010\005\000\002\010\005\000\002\010\003\000\002\011" +
    "\005\000\002\011\003\000\002\015\003\000\002\015\003" +
    "\000\002\015\003\000\002\015\003\000\002\015\003\000" +
    "\002\015\003\000\002\012\005\000\002\012\005\000\002" +
    "\012\003\000\002\013\005\000\002\013\005\000\002\013" +
    "\003\000\002\014\005\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\006\007\005\010\004\001\002\000\004\006" +
    "\071\001\002\000\004\006\070\001\002\000\004\002\067" +
    "\001\002\000\006\004\ufffe\005\ufffe\001\002\000\006\004" +
    "\012\005\011\001\002\000\006\007\005\010\004\001\002" +
    "\000\004\006\014\001\002\000\006\002\001\005\064\001" +
    "\002\000\004\015\016\001\002\000\006\002\ufffa\005\ufffa" +
    "\001\002\000\020\006\020\011\022\012\024\016\032\020" +
    "\017\023\021\033\023\001\002\000\014\006\020\011\022" +
    "\012\024\023\021\033\023\001\002\000\040\002\uffe3\005" +
    "\uffe3\013\uffe3\014\uffe3\016\uffe3\017\uffe3\021\uffe3\022\uffe3" +
    "\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3\032" +
    "\uffe3\001\002\000\020\006\020\011\022\012\024\016\032" +
    "\020\017\023\021\033\023\001\002\000\040\002\uffe2\005" +
    "\uffe2\013\uffe2\014\uffe2\016\uffe2\017\uffe2\021\uffe2\022\uffe2" +
    "\024\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\032" +
    "\uffe2\001\002\000\040\002\uffe0\005\uffe0\013\uffe0\014\uffe0" +
    "\016\uffe0\017\uffe0\021\uffe0\022\uffe0\024\uffe0\025\uffe0\026" +
    "\uffe0\027\uffe0\030\uffe0\031\uffe0\032\uffe0\001\002\000\040" +
    "\002\uffe1\005\uffe1\013\uffe1\014\uffe1\016\uffe1\017\uffe1\021" +
    "\uffe1\022\uffe1\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030\uffe1" +
    "\031\uffe1\032\uffe1\001\002\000\006\002\ufff9\005\ufff9\001" +
    "\002\000\014\002\ufff6\005\ufff6\021\055\022\056\024\ufff6" +
    "\001\002\000\014\002\ufff3\005\ufff3\021\ufff3\022\ufff3\024" +
    "\ufff3\001\002\000\030\002\ufff1\005\ufff1\021\ufff1\022\ufff1" +
    "\024\ufff1\025\050\026\051\027\052\030\053\031\046\032" +
    "\045\001\002\000\040\002\uffe8\005\uffe8\013\037\014\035" +
    "\016\040\017\036\021\uffe8\022\uffe8\024\uffe8\025\uffe8\026" +
    "\uffe8\027\uffe8\030\uffe8\031\uffe8\032\uffe8\001\002\000\020" +
    "\006\020\011\022\012\024\016\032\020\017\023\021\033" +
    "\023\001\002\000\040\002\uffe5\005\uffe5\013\uffe5\014\uffe5" +
    "\016\uffe5\017\uffe5\021\uffe5\022\uffe5\024\uffe5\025\uffe5\026" +
    "\uffe5\027\uffe5\030\uffe5\031\uffe5\032\uffe5\001\002\000\010" +
    "\002\ufff8\005\ufff8\024\ufff8\001\002\000\014\006\020\011" +
    "\022\012\024\023\021\033\023\001\002\000\014\006\020" +
    "\011\022\012\024\023\021\033\023\001\002\000\014\006" +
    "\020\011\022\012\024\023\021\033\023\001\002\000\014" +
    "\006\020\011\022\012\024\023\021\033\023\001\002\000" +
    "\040\002\uffe6\005\uffe6\013\uffe6\014\uffe6\016\uffe6\017\uffe6" +
    "\021\uffe6\022\uffe6\024\uffe6\025\uffe6\026\uffe6\027\uffe6\030" +
    "\uffe6\031\uffe6\032\uffe6\001\002\000\030\002\uffea\005\uffea" +
    "\021\uffea\022\uffea\024\uffea\025\uffea\026\uffea\027\uffea\030" +
    "\uffea\031\uffea\032\uffea\001\002\000\040\002\uffe7\005\uffe7" +
    "\013\uffe7\014\uffe7\016\uffe7\017\uffe7\021\uffe7\022\uffe7\024" +
    "\uffe7\025\uffe7\026\uffe7\027\uffe7\030\uffe7\031\uffe7\032\uffe7" +
    "\001\002\000\034\002\uffe9\005\uffe9\016\040\017\036\021" +
    "\uffe9\022\uffe9\024\uffe9\025\uffe9\026\uffe9\027\uffe9\030\uffe9" +
    "\031\uffe9\032\uffe9\001\002\000\014\006\uffeb\011\uffeb\012" +
    "\uffeb\023\uffeb\033\uffeb\001\002\000\014\006\ufff0\011\ufff0" +
    "\012\ufff0\023\ufff0\033\ufff0\001\002\000\014\006\020\011" +
    "\022\012\024\023\021\033\023\001\002\000\014\006\uffec" +
    "\011\uffec\012\uffec\023\uffec\033\uffec\001\002\000\014\006" +
    "\uffed\011\uffed\012\uffed\023\uffed\033\uffed\001\002\000\014" +
    "\006\uffef\011\uffef\012\uffef\023\uffef\033\uffef\001\002\000" +
    "\014\006\uffee\011\uffee\012\uffee\023\uffee\033\uffee\001\002" +
    "\000\014\002\ufff2\005\ufff2\021\ufff2\022\ufff2\024\ufff2\001" +
    "\002\000\014\006\020\011\022\012\024\023\021\033\023" +
    "\001\002\000\014\006\020\011\022\012\024\023\021\033" +
    "\023\001\002\000\014\002\ufff4\005\ufff4\021\ufff4\022\ufff4" +
    "\024\ufff4\001\002\000\014\002\ufff5\005\ufff5\021\ufff5\022" +
    "\ufff5\024\ufff5\001\002\000\004\024\062\001\002\000\040" +
    "\002\uffe4\005\uffe4\013\uffe4\014\uffe4\016\uffe4\017\uffe4\021" +
    "\uffe4\022\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4\030\uffe4" +
    "\031\uffe4\032\uffe4\001\002\000\014\002\ufff7\005\ufff7\021" +
    "\055\022\056\024\ufff7\001\002\000\004\006\014\001\002" +
    "\000\006\002\ufffb\005\ufffb\001\002\000\006\004\uffff\005" +
    "\uffff\001\002\000\004\002\000\001\002\000\006\004\ufffd" +
    "\005\ufffd\001\002\000\006\004\ufffc\005\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\010\002\005\003\007\004\006\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\004\065\001\001\000" +
    "\006\005\012\006\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\007\024\010\025\011" +
    "\026\012\027\013\030\014\032\001\001\000\014\010\062" +
    "\011\026\012\027\013\030\014\032\001\001\000\002\001" +
    "\001\000\016\007\060\010\025\011\026\012\027\013\030" +
    "\014\032\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\015\046\001\001\000\002\001\001\000" +
    "\016\007\033\010\025\011\026\012\027\013\030\014\032" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\013" +
    "\043\014\032\001\001\000\004\014\042\001\001\000\010" +
    "\012\041\013\030\014\032\001\001\000\004\014\040\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\012\053\013\030\014\032\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\011\057\012\027\013\030\014\032" +
    "\001\001\000\012\011\056\012\027\013\030\014\032\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\064\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoTiny$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoTiny$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoTiny$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {


	errores = new GestionErroresTiny();
	AnalizadorLexicoTiny alex = (AnalizadorLexicoTiny)getScanner();
	alex.fijaGestionErrores(errores);


    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }



	private GestionErroresTiny errores;
	public void syntax_error(Symbol unidadLexica) {
		System.out.println("ERROR");
		errores.errorSintactico((UnidadLexica)unidadLexica);
	}
	public static void main(String[] args) throws Exception {
	    Reader input = new InputStreamReader(new FileInputStream("src/pruebas/correcto.txt"));
		AnalizadorLexicoTiny alex = new AnalizadorLexicoTiny(input);
		AnalizadorSintacticoTiny asint = new AnalizadorSintacticoTiny(alex);
		// asint.parse();
		System.out.println("ASCENDENTE:");
		System.out.println(asint.parse().value);
		System.out.println("¡¡CORRECTO!!");
	}

	// java -jar cup.jar -expect 31 -nopositions -parser AnalizadorSintacticoTiny -symbols ClaseLexica Tiny.cup

	public static E mkexp(String lex, E e0, E e1) {
		if(lex.equalsIgnoreCase("==")) {
			return new OpIgual(e0, e1);
		} else if(lex.equalsIgnoreCase("!=")) {
			return new OpDistinto(e0, e1);
		} else if(lex.equalsIgnoreCase("<")) {
			return new OpMenor(e0, e1);
		} else if(lex.equalsIgnoreCase(">")) {
			return new OpMayor(e0, e1);
		} else if(lex.equalsIgnoreCase("<=")) {
			return new OpMenorIgual(e0, e1);
		} else if(lex.equalsIgnoreCase("=>")) {
			return new OpMayorIgual(e0, e1);
		} else {
			return null;
		}
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoTiny$actions {
  private final AnalizadorSintacticoTiny parser;

  /** Constructor */
  CUP$AnalizadorSintacticoTiny$actions(AnalizadorSintacticoTiny parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$do_action_part00000000(
    int                        CUP$AnalizadorSintacticoTiny$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoTiny$parser,
    java.util.Stack            CUP$AnalizadorSintacticoTiny$stack,
    int                        CUP$AnalizadorSintacticoTiny$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoTiny$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // S ::= D SEPARADOR I 
            {
              Object RESULT =null;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new Programa((D)d, (I)i);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("S",0, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= S EOF 
            {
              Object RESULT =null;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoTiny$parser.done_parsing();
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // D ::= D PUNTOYCOMA DS 
            {
              Object RESULT =null;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object ds = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new DCompuesta((DS)ds, (D)d);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("D",1, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // D ::= DS 
            {
              Object RESULT =null;
		Object ds = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new DSimple((DS)ds);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("D",1, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // DS ::= NOMBRETIPONUM NOMBREVARIABLE 
            {
              Object RESULT =null;
		Object nv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new DNum((String)nv);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("DS",2, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // DS ::= NOMBRETIPOBOOL NOMBREVARIABLE 
            {
              Object RESULT =null;
		Object nv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new DBool((String)nv);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("DS",2, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // I ::= I PUNTOYCOMA IS 
            {
              Object RESULT =null;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object is = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new ACompuesta((IS)is, (I)i);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("I",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // I ::= IS 
            {
              Object RESULT =null;
		Object is = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new ASimple((IS)is);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("I",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // IS ::= NOMBREVARIABLE OPASIGNAR E4 
            {
              Object RESULT =null;
		Object nv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object e4 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new Asignacion((String)nv, (E)e4);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("IS",4, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // E4 ::= OPMENOSUNARIO E4 
            {
              Object RESULT =null;
		Object e4 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpMenosUnario((E)e4);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",5, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // E4 ::= OPNOT E3 
            {
              Object RESULT =null;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpNot((E)e3);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",5, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // E4 ::= E3 
            {
              Object RESULT =null;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (E)e3;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",5, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // E3 ::= E3 OPMUL E2 
            {
              Object RESULT =null;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpMul((E)e3, (E)e2);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",6, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // E3 ::= E3 OPDIV E2 
            {
              Object RESULT =null;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpDiv((E)e3, (E)e2);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",6, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // E3 ::= E2 
            {
              Object RESULT =null;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (E)e2;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",6, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // E2 ::= E1 R E1 
            {
              Object RESULT =null;
		Object e10 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		Object e11 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = AnalizadorSintacticoTiny.mkexp((String)r, (E)e10, (E)e11);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E2",7, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // E2 ::= E1 
            {
              Object RESULT =null;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (E)e1;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E2",7, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // R ::= OPIGUAL 
            {
              Object RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (String)op;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("R",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // R ::= OPMENORIGUAL 
            {
              Object RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (String)op;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("R",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // R ::= OPMAYORIGUAL 
            {
              Object RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (String)op;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("R",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // R ::= OPMAYOR 
            {
              Object RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (String)op;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("R",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // R ::= OPMENOR 
            {
              Object RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (String)op;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("R",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // R ::= OPDISTINTO 
            {
              Object RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (String)op;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("R",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // E1 ::= E0 OPAND E1 
            {
              Object RESULT =null;
		Object e0 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpAnd((E)e0, (E)e1);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // E1 ::= E0 OPOR E0 
            {
              Object RESULT =null;
		Object e01 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object e02 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpOr((E)e01, (E)e02);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // E1 ::= E0 
            {
              Object RESULT =null;
		Object e0 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = (E)e0;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // E0 ::= E0 OPMAS F 
            {
              Object RESULT =null;
		Object e0 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpMas((E)e0, (E)f);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",9, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // E0 ::= E0 OPMENOSUNARIO F 
            {
              Object RESULT =null;
		Object e0 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new OpMenos((E)e0, (E)f);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",9, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // E0 ::= F 
            {
              Object RESULT =null;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = f;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",9, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // F ::= PAP E4 PCI 
            {
              Object RESULT =null;
		Object e4 = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		RESULT = (E)e4;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("F",10, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // F ::= NOMBREVARIABLE 
            {
              Object RESULT =null;
		Object nv = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new NombreVariable((String)nv);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("F",10, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // F ::= TRUE 
            {
              Object RESULT =null;
		RESULT = new BoolTrue();
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("F",10, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // F ::= FALSE 
            {
              Object RESULT =null;
		RESULT = new BoolFalse();
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("F",10, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // F ::= NUMERO 
            {
              Object RESULT =null;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		RESULT = new Numero((String)n);
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("F",10, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSintacticoTiny$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$do_action(
    int                        CUP$AnalizadorSintacticoTiny$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoTiny$parser,
    java.util.Stack            CUP$AnalizadorSintacticoTiny$stack,
    int                        CUP$AnalizadorSintacticoTiny$top)
    throws java.lang.Exception
    {
              return CUP$AnalizadorSintacticoTiny$do_action_part00000000(
                               CUP$AnalizadorSintacticoTiny$act_num,
                               CUP$AnalizadorSintacticoTiny$parser,
                               CUP$AnalizadorSintacticoTiny$stack,
                               CUP$AnalizadorSintacticoTiny$top);
    }
}

