
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 03 16:02:46 CEST 2019
//----------------------------------------------------

package ascendente.asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PUNTOYCOMA = 3;
  public static final int NOMBREVARIABLE = 4;
  public static final int OPMAYOR = 20;
  public static final int OPOR = 10;
  public static final int NOMBRETIPOBOOL = 6;
  public static final int OPDIV = 16;
  public static final int TRUE = 7;
  public static final int NOMBRETIPONUM = 5;
  public static final int OPMAYORIGUAL = 22;
  public static final int PCI = 18;
  public static final int SEPARADOR = 2;
  public static final int EOF = 0;
  public static final int OPMUL = 15;
  public static final int OPMAS = 13;
  public static final int OPMENOR = 19;
  public static final int PAP = 17;
  public static final int FALSE = 8;
  public static final int NUMERO = 25;
  public static final int error = 1;
  public static final int OPAND = 9;
  public static final int OPIGUAL = 23;
  public static final int OPDISTINTO = 24;
  public static final int OPNOT = 14;
  public static final int OPMENOSUNARIO = 12;
  public static final int OPMENORIGUAL = 21;
  public static final int OPASIGNAR = 11;
}

